<a href="https://colab.research.google.com/github/prekhanshi/Experiment--7-Study-of-For-Loop-and-While-Loop-in-Python/blob/main/exp13.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Name: Prekhanshi kumbhhakar
#PRN: 25070123151
#branch: ENTC
#batch: A1
#EXPERIMENT NO. 13
#TITLE: Data binning and data formating using pyhton
#date: 20/03/26

In [ ]:
import pandas as pd
import numpy as np

data= {
    'product':['computer','printer','monitor','tablet','smartwatch','camera'],
    'price':[55000,10000,15000,5000,8000,45000],
    'units_sold':[24,50,5,34,10,60]
}
df = pd.DataFrame(data)
print(df)

      product  price  units_sold
0    computer  55000          24
1     printer  10000          50
2     monitor  15000           5
3      tablet   5000          34
4  smartwatch   8000          10
5      camera  45000          60

In [ ]:
#data binning
bins = [0,5000,15000, 55000,]
labels = ['low','medium','high']
df['price_category'] = pd.cut(df['price'],bins=bins, labels=labels)
df

      product  price  units_sold price_category
0    computer  55000          24           high
1     printer  10000          50         medium
2     monitor  15000           5         medium
3      tablet   5000          34            low
4  smartwatch   8000          10         medium
5      camera  45000          60           high

In [ ]:
#binning units sold
bins2=[0,5,30,60]
labels2=['low','medium','high']
df['sales_category'] = pd.cut(df['units_sold'],bins=bins2, labels=labels2)
df

      product  price  units_sold price_category sales_category
0    computer  55000          24           high         medium
1     printer  10000          50         medium           high
2     monitor  15000           5         medium            low
3      tablet   5000          34            low           high
4  smartwatch   8000          10         medium         medium
5      camera  45000          60           high           high

In [ ]:
#data fromatting
#convert data type
print(df.dtypes)
df['units_sold'] = df['units_sold'].astype(float)
print(df.dtypes)

product             object
price                int64
units_sold           int64
price_category    category
sales_category    category
dtype: object
product             object
price                int64
units_sold         float64
price_category    category
sales_category    category
dtype: object

In [ ]:
#convert text to uppercase
df['product'] = df['product'].str.upper()
df

      product  price  units_sold price_category sales_category
0    COMPUTER  55000        24.0           high         medium
1     PRINTER  10000        50.0         medium           high
2     MONITOR  15000         5.0         medium            low
3      TABLET   5000        34.0            low           high
4  SMARTWATCH   8000        10.0         medium         medium
5      CAMERA  45000        60.0           high           high

In [ ]:
#rounding values
df['price'] = df['price'].round(2)
df

      product  price  units_sold price_category sales_category
0    COMPUTER  55000        24.0           high         medium
1     PRINTER  10000        50.0         medium           high
2     MONITOR  15000         5.0         medium            low
3      TABLET   5000        34.0            low           high
4  SMARTWATCH   8000        10.0         medium         medium
5      CAMERA  45000        60.0           high           high

In [ ]:
#additional operations
#sort data
sorted_df = df.sort_values(by='price')
print(sorted_df)

      product  price  units_sold price_category sales_category
3      TABLET   5000        34.0            low           high
4  SMARTWATCH   8000        10.0         medium         medium
1     PRINTER  10000        50.0         medium           high
2     MONITOR  15000         5.0         medium            low
5      CAMERA  45000        60.0           high           high
0    COMPUTER  55000        24.0           high         medium

In [ ]:
#display unique values
print(df['price_category'].unique())

['high', 'medium', 'low']
Categories (3, object): ['low' < 'medium' < 'high']

In [ ]:
#dataset :food delivery orders
import pandas as pd
import numpy as np
data = {
    'order_ID':['01','02','03','04','05','06','07','08'],
    'order_value':[250,450,120,600,300,150,509,220],
    'delivery_time':[30,45,35,60,20,50,75,27],
    'distance_km':[5,7,9,20,10,3,5,4]
}
df = pd.DataFrame(data)
print(df)

  order_ID  order_value  delivery_time  distance_km
0       01          250             30            5
1       02          450             45            7
2       03          120             35            9
3       04          600             60           20
4       05          300             20           10
5       06          150             50            3
6       07          509             75            5
7       08          220             27            4

In [ ]:
#binning order value
bins = [0,100,200,400]
labels = ['low','medium','high']
df['order_category'] = pd.cut(df['order_value'],bins=bins, labels=labels)
df

  order_ID  order_value  delivery_time  distance_km order_category
0       01          250             30            5           high
1       02          450             45            7            NaN
2       03          120             35            9         medium
3       04          600             60           20            NaN
4       05          300             20           10           high
5       06          150             50            3         medium
6       07          509             75            5            NaN
7       08          220             27            4           high

In [ ]:
#binning delivery time
bins2=[0,30,45,70]
labels2=['fast','medium','slow']
df['delivery_category'] = pd.cut(df['delivery_time'], bins=bins2, labels=labels2)
df

,order_ID,order_value,delivery_time,distance_km,order_category,delivery_category
0,01,250,30,5,high,fast
1,02,450,45,7,NaN,medium
2,03,120,35,9,medium,medium
3,04,600,60,20,NaN,slow
4,05,300,20,10,high,fast
5,06,150,50,3,medium,slow
6,07,509,75,5,NaN,NaN
7,08,220,27,4,high,fast

In [ ]:
#unique categories
print(df['order_category'].unique())

['high', NaN, 'medium']
Categories (3, object): ['low' < 'medium' < 'high']

In [ ]:
#count of categories
print(df['order_category'].value_counts())

order_category
high      3
medium    2
low       0
Name: count, dtype: int64

In [ ]:
#sorting
print(df.sort_values(by='order_value'))

  order_ID  order_value  delivery_time  distance_km order_category  \
2       03          120             35            9         medium
5       06          150             50            3         medium
7       08          220             27            4           high
0       01          250             30            5           high
4       05          300             20           10           high
1       02          450             45            7            NaN
6       07          509             75            5            NaN
3       04          600             60           20            NaN

  delivery_category
2            medium
5              slow
7              fast
0              fast
4              fast
1            medium
6               NaN
3              slow